version: '3.8'

services:
  
  database: 
    container_name: database
    restart: unless-stopped
    build: database
    command: [
      '--wait_timeout=28800',
    ]
  main:
    container_name: main
    restart: unless-stopped
    build: main
    depends_on:
      - database
