FROM mysql
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=jpetstore
COPY 01-jpetstore-hsqldb-schema.sql /docker-entrypoint-initdb.d/
COPY 02-jpetstore-hsqldb-dataload.sql /docker-entrypoint-initdb.d/
