FROM mysql
WORKDIR /docker-entrypoint-initdb.d
EXPOSE 3306
ENV MYSQL_ROOT_USER=root
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=jpetstore
ENV TZ="Asia/Taipei"
ADD jpetstore-hsqldb-schema.sql .
ADD jpetstore-hsqldb-dataload.sql .
